dbdata:
  image: normalised/data-container
  volumes:
    - ./mysql_data:/var/lib/mysql

db:
  image: mysql
  volumes_from:
    - dbdata
  ports:
    - "3306:3306"
  expose:
    - "3306"
  environment:
    MYSQL_DATABASE: "bacron"
    MYSQL_USER: "pr0k"
    MYSQL_PASSWORD: "bacron"
    MYSQL_ROOT_PASSWORD: "bacron"

app:
  image: normalised/bacron
  volumes:
    - ./media:/media
  links:
    - db